import BlogsModule from '@/modules/BlogsModule/BlogsModule'
import Head from 'next/head'


export default function Course() {
  return (
    <>
      <Head>
        <title>BrainXskill | Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BlogsModule/>
    </>
  )
}