import HomeModule from '@/modules/HomeModule'
import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>BrainXskill | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://nexusautotransport.com/" rel="canonical"></link>
        <link href="https://nexusautotransport.com/" rel="home"></link>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="keywords" content="BootCamp, Web Development, frontend development, backend development, Databases, Data Structures, Data Sciene  ,machine , learning,  framework , Ui/Ux developer , HTML , CSS3, JavaScript, React , Node.js , MongoDB"/>
      </Head>

      00281008678069
      <HomeModule />
    </>
  )
}
