import SuccessModule from '@/modules/SuccessModule/SuccessModule'
import Head from 'next/head'


export default function Success() {
  return (
    <>
      <Head>
        <title>BrainXskill | Success</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SuccessModule/>
    </>
  )
}